language: java
jdk:
  - openjdk8

cache:
  directories:  # run "travis cache --delete" to delete caches
    - $HOME/.gradle

sudo: false
script:
  - ./gradlew --info checkstyle
  - ./gradlew --info check

# after_success: ./gradlew sonarqube -Dsonar.organization=yuokada-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN}
